package de.greenrobot.BcComicdao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BC_INDEX_DATA".
 */
@Entity
public class BcIndexData {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String PKUrl;

    @NotNull
    private String HomePK;
    private String ImageUrl;

    @NotNull
    private String TitleName;
    private String AuthorName;
    private String Updated_day;
    private String Type="";
    private String Gist;
    private Boolean isCollect;
    private String ItemArrayGSON;
    private java.util.Date ClickDate;
    private Integer FocusItem;
    private String ComicDownloadPath;
    private Boolean isDownload;

    @Generated(hash = 1421209397)
    public BcIndexData() {
    }

    public BcIndexData(Long id) {
        this.id = id;
    }

    @Generated(hash = 824009644)
    public BcIndexData(Long id, @NotNull String PKUrl, @NotNull String HomePK, String ImageUrl, @NotNull String TitleName, String AuthorName, String Updated_day, String Type, String Gist, Boolean isCollect, String ItemArrayGSON, java.util.Date ClickDate, Integer FocusItem,
            String ComicDownloadPath, Boolean isDownload) {
        this.id = id;
        this.PKUrl = PKUrl;
        this.HomePK = HomePK;
        this.ImageUrl = ImageUrl;
        this.TitleName = TitleName;
        this.AuthorName = AuthorName;
        this.Updated_day = Updated_day;
        this.Type = Type;
        this.Gist = Gist;
        this.isCollect = isCollect;
        this.ItemArrayGSON = ItemArrayGSON;
        this.ClickDate = ClickDate;
        this.FocusItem = FocusItem;
        this.ComicDownloadPath = ComicDownloadPath;
        this.isDownload = isDownload;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getPKUrl() {
        return PKUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPKUrl(@NotNull String PKUrl) {
        this.PKUrl = PKUrl;
    }

    @NotNull
    public String getHomePK() {
        return HomePK;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHomePK(@NotNull String HomePK) {
        this.HomePK = HomePK;
    }

    public String getImageUrl() {
        return ImageUrl;
    }

    public void setImageUrl(String ImageUrl) {
        this.ImageUrl = ImageUrl;
    }

    @NotNull
    public String getTitleName() {
        return TitleName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitleName(@NotNull String TitleName) {
        this.TitleName = TitleName;
    }

    public String getAuthorName() {
        return AuthorName;
    }

    public void setAuthorName(String AuthorName) {
        this.AuthorName = AuthorName;
    }

    public String getUpdated_day() {
        return Updated_day;
    }

    public void setUpdated_day(String Updated_day) {
        this.Updated_day = Updated_day;
    }

    public String getType() {
        return Type;
    }

    public void setType(String Type) {
        this.Type = Type;
    }

    public String getGist() {
        return Gist;
    }

    public void setGist(String Gist) {
        this.Gist = Gist;
    }

    public Boolean getIsCollect() {
        return isCollect;
    }

    public void setIsCollect(Boolean isCollect) {
        this.isCollect = isCollect;
    }

    public String getItemArrayGSON() {
        return ItemArrayGSON;
    }

    public void setItemArrayGSON(String ItemArrayGSON) {
        this.ItemArrayGSON = ItemArrayGSON;
    }

    public java.util.Date getClickDate() {
        return ClickDate;
    }

    public void setClickDate(java.util.Date ClickDate) {
        this.ClickDate = ClickDate;
    }

    public Integer getFocusItem() {
        return FocusItem;
    }

    public void setFocusItem(Integer FocusItem) {
        this.FocusItem = FocusItem;
    }

    public String getComicDownloadPath() {
        return ComicDownloadPath;
    }

    public void setComicDownloadPath(String ComicDownloadPath) {
        this.ComicDownloadPath = ComicDownloadPath;
    }

    public Boolean getIsDownload() {
        return isDownload;
    }

    public void setIsDownload(Boolean isDownload) {
        this.isDownload = isDownload;
    }

}
