package de.greenrobot.BcComicdao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BC_SORT_DATA".
 */
@Entity
public class BcSortData {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    @Unique
    private String HomePK;
    private String SortUrl;
    private String SortItemArrayGSON;
    private java.util.Date LastUpdated;

    @Generated(hash = 633239372)
    public BcSortData() {
    }

    public BcSortData(Long id) {
        this.id = id;
    }

    @Generated(hash = 664706932)
    public BcSortData(Long id, @NotNull String HomePK, String SortUrl, String SortItemArrayGSON,
            java.util.Date LastUpdated) {
        this.id = id;
        this.HomePK = HomePK;
        this.SortUrl = SortUrl;
        this.SortItemArrayGSON = SortItemArrayGSON;
        this.LastUpdated = LastUpdated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getHomePK() {
        return HomePK;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHomePK(@NotNull String HomePK) {
        this.HomePK = HomePK;
    }

    public String getSortUrl() {
        return SortUrl;
    }

    public void setSortUrl(String SortUrl) {
        this.SortUrl = SortUrl;
    }

    public String getSortItemArrayGSON() {
        return SortItemArrayGSON;
    }

    public void setSortItemArrayGSON(String SortItemArrayGSON) {
        this.SortItemArrayGSON = SortItemArrayGSON;
    }

    public java.util.Date getLastUpdated() {
        return LastUpdated;
    }

    public void setLastUpdated(java.util.Date LastUpdated) {
        this.LastUpdated = LastUpdated;
    }

}
