package de.greenrobot.BcComicdao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BC_SORT_DATA".
*/
public class BcSortDataDao extends AbstractDao<BcSortData, Long> {

    public static final String TABLENAME = "BC_SORT_DATA";

    /**
     * Properties of entity BcSortData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property HomePK = new Property(1, String.class, "HomePK", false, "HOME_PK");
        public final static Property SortUrl = new Property(2, String.class, "SortUrl", false, "SORT_URL");
        public final static Property SortItemArrayGSON = new Property(3, String.class, "SortItemArrayGSON", false, "SORT_ITEM_ARRAY_GSON");
        public final static Property LastUpdated = new Property(4, java.util.Date.class, "LastUpdated", false, "LAST_UPDATED");
    }


    public BcSortDataDao(DaoConfig config) {
        super(config);
    }
    
    public BcSortDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BC_SORT_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"HOME_PK\" TEXT NOT NULL UNIQUE ," + // 1: HomePK
                "\"SORT_URL\" TEXT," + // 2: SortUrl
                "\"SORT_ITEM_ARRAY_GSON\" TEXT," + // 3: SortItemArrayGSON
                "\"LAST_UPDATED\" INTEGER);"); // 4: LastUpdated
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BC_SORT_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BcSortData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getHomePK());
 
        String SortUrl = entity.getSortUrl();
        if (SortUrl != null) {
            stmt.bindString(3, SortUrl);
        }
 
        String SortItemArrayGSON = entity.getSortItemArrayGSON();
        if (SortItemArrayGSON != null) {
            stmt.bindString(4, SortItemArrayGSON);
        }
 
        java.util.Date LastUpdated = entity.getLastUpdated();
        if (LastUpdated != null) {
            stmt.bindLong(5, LastUpdated.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BcSortData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getHomePK());
 
        String SortUrl = entity.getSortUrl();
        if (SortUrl != null) {
            stmt.bindString(3, SortUrl);
        }
 
        String SortItemArrayGSON = entity.getSortItemArrayGSON();
        if (SortItemArrayGSON != null) {
            stmt.bindString(4, SortItemArrayGSON);
        }
 
        java.util.Date LastUpdated = entity.getLastUpdated();
        if (LastUpdated != null) {
            stmt.bindLong(5, LastUpdated.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BcSortData readEntity(Cursor cursor, int offset) {
        BcSortData entity = new BcSortData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // HomePK
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // SortUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // SortItemArrayGSON
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)) // LastUpdated
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BcSortData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setHomePK(cursor.getString(offset + 1));
        entity.setSortUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSortItemArrayGSON(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLastUpdated(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BcSortData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BcSortData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BcSortData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
